// <auto-generated />
using System;
using Mercadona.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercadona.Migrations
{
    [DbContext(typeof(MercadonaContext))]
    partial class MercadonaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mercadona.Models.Categorie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nom")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ctgcategorie", (string)null);
                });

            modelBuilder.Entity("Mercadona.Models.Produit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Categorieid")
                        .HasColumnType("integer");

                    b.Property<int?>("Promotionid")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<int>("prd_ctg_id")
                        .HasColumnType("integer");

                    b.Property<int?>("prd_prm_id")
                        .HasColumnType("integer");

                    b.Property<float?>("prix")
                        .HasColumnType("real");

                    b.Property<string>("titre")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Categorieid");

                    b.HasIndex("Promotionid");

                    b.ToTable("prdproduit", (string)null);
                });

            modelBuilder.Entity("Mercadona.Models.Promotion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datedebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("datefin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pctpromotion")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("prmpromotion", (string)null);
                });

            modelBuilder.Entity("Mercadona.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("mdp")
                        .HasColumnType("text");

                    b.Property<string>("nom")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("usrutilisateur", (string)null);
                });

            modelBuilder.Entity("Mercadona.Models.Produit", b =>
                {
                    b.HasOne("Mercadona.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("Categorieid");

                    b.HasOne("Mercadona.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("Promotionid");

                    b.Navigation("Categorie");

                    b.Navigation("Promotion");
                });
#pragma warning restore 612, 618
        }
    }
}
