name: masquer la chaine de connexion
on: push
jobs:
  hide-secret:
    runs-on: ubuntu-latest
    steps:
      - name: voir arborescence
        run: ls -a
      - name: masquage
        run: sed -i -e "s/${{secrets.SECRET_CONNEXIONSTRING}}/****/g" appsettings.json
      
  
